"""empty message

Revision ID: 59cf9b9de7bd
Revises: 8a896a87fe1c
Create Date: 2018-03-08 11:33:00.522982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cf9b9de7bd'
down_revision = '8a896a87fe1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('dna_bidning_data', 'dna_binding_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
