"""empty message

Revision ID: 962381af9b31
Revises: c1b048bba3fa
Create Date: 2018-03-06 18:23:11.691813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '962381af9b31'
down_revision = 'c1b048bba3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('protein_subunit', sa.Column('uniprot_checked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('protein_subunit', 'uniprot_checked')
    # ### end Alembic commands ###
