"""empty message

Revision ID: 9d93c2eb77da
Revises: 59cf9b9de7bd
Create Date: 2018-04-23 16:54:47.010449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d93c2eb77da'
down_revision = '59cf9b9de7bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concentration', sa.Column('units', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_dna_binding_data_position'), 'dna_binding_data', ['position'], unique=False)
    op.drop_index('ix_dna_bidning_data_position', table_name='dna_binding_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_dna_bidning_data_position', 'dna_binding_data', ['position'], unique=False)
    op.drop_index(op.f('ix_dna_binding_data_position'), table_name='dna_binding_data')
    op.drop_column('concentration', 'units')
    # ### end Alembic commands ###
