"""empty message

Revision ID: d689b23367a9
Revises: ea8e6d48cd86
Create Date: 2018-02-26 16:18:00.539622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd689b23367a9'
down_revision = 'ea8e6d48cd86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_experimentmetadata',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_format',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('bio_assay_data_cubes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('experiment_design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_experimentmetadata_experimentdesign',
    sa.Column('_experimentmetadata_id', sa.Integer(), nullable=True),
    sa.Column('experiment_design_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_experimentmetadata_id'], ['_experimentmetadata.id'], ),
    sa.ForeignKeyConstraint(['experiment_design_id'], ['experiment_design.id'], )
    )
    op.create_index(op.f('ix__experimentmetadata_experimentdesign__experimentmetadata_id'), '_experimentmetadata_experimentdesign', ['_experimentmetadata_id'], unique=False)
    op.create_index(op.f('ix__experimentmetadata_experimentdesign_experiment_design_id'), '_experimentmetadata_experimentdesign', ['experiment_design_id'], unique=False)
    op.create_table('_experimentmetadata_experimenttype',
    sa.Column('_experimentmetadata_id', sa.Integer(), nullable=True),
    sa.Column('experiment_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_experimentmetadata_id'], ['_experimentmetadata.id'], ),
    sa.ForeignKeyConstraint(['experiment_type_id'], ['experiment_type.id'], )
    )
    op.create_index(op.f('ix__experimentmetadata_experimenttype__experimentmetadata_id'), '_experimentmetadata_experimenttype', ['_experimentmetadata_id'], unique=False)
    op.create_index(op.f('ix__experimentmetadata_experimenttype_experiment_type_id'), '_experimentmetadata_experimenttype', ['experiment_type_id'], unique=False)
    op.create_table('_experimentmetadata_method',
    sa.Column('_experimentmetadata_id', sa.Integer(), nullable=True),
    sa.Column('method_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_experimentmetadata_id'], ['_experimentmetadata.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['method.id'], )
    )
    op.create_index(op.f('ix__experimentmetadata_method__experimentmetadata_id'), '_experimentmetadata_method', ['_experimentmetadata_id'], unique=False)
    op.create_index(op.f('ix__experimentmetadata_method_method_id'), '_experimentmetadata_method', ['method_id'], unique=False)
    op.create_table('_experimentmetadata_resource',
    sa.Column('_experimentmetadata_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_experimentmetadata_id'], ['_experimentmetadata.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], )
    )
    op.create_index(op.f('ix__experimentmetadata_resource__experimentmetadata_id'), '_experimentmetadata_resource', ['_experimentmetadata_id'], unique=False)
    op.create_index(op.f('ix__experimentmetadata_resource_resource_id'), '_experimentmetadata_resource', ['resource_id'], unique=False)
    op.create_table('_experimentmetadata_taxon',
    sa.Column('_experimentmetadata_id', sa.Integer(), nullable=True),
    sa.Column('taxon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_experimentmetadata_id'], ['_experimentmetadata.id'], ),
    sa.ForeignKeyConstraint(['taxon_id'], ['taxon.ncbi_id'], )
    )
    op.create_index(op.f('ix__experimentmetadata_taxon__experimentmetadata_id'), '_experimentmetadata_taxon', ['_experimentmetadata_id'], unique=False)
    op.create_index(op.f('ix__experimentmetadata_taxon_taxon_id'), '_experimentmetadata_taxon', ['taxon_id'], unique=False)
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_experimentmetadata_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['_experimentmetadata_id'], ['_experimentmetadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reference_genome',
    sa.Column('reference_genome_id', sa.Integer(), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('organism_strain', sa.String(length=255), nullable=True),
    sa.Column('download_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['reference_genome_id'], ['physical_property.observation_id'], ),
    sa.PrimaryKeyConstraint('reference_genome_id')
    )
    op.create_table('rnaseqdataset_referencegenome',
    sa.Column('sample_id', sa.Integer(), nullable=True),
    sa.Column('reference_genome_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reference_genome_id'], ['reference_genome.reference_genome_id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['rna_seq_dataset.sample_id'], )
    )
    op.create_index(op.f('ix_rnaseqdataset_referencegenome_reference_genome_id'), 'rnaseqdataset_referencegenome', ['reference_genome_id'], unique=False)
    op.create_index(op.f('ix_rnaseqdataset_referencegenome_sample_id'), 'rnaseqdataset_referencegenome', ['sample_id'], unique=False)
    op.drop_column(u'_metadata', 'description')
    op.add_column(u'rna_seq_experiment', sa.Column('accession_number', sa.String(), nullable=True))
    op.drop_constraint(None, 'rna_seq_experiment', type_='foreignkey')
    op.create_foreign_key(None, 'rna_seq_experiment', 'experiment', ['experiment_id'], ['id'])
    op.drop_column(u'rna_seq_experiment', 'accesion_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'rna_seq_experiment', sa.Column('accesion_number', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'rna_seq_experiment', type_='foreignkey')
    op.create_foreign_key(None, 'rna_seq_experiment', 'physical_property', ['experiment_id'], ['observation_id'])
    op.drop_column(u'rna_seq_experiment', 'accession_number')
    op.add_column(u'_metadata', sa.Column('description', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_rnaseqdataset_referencegenome_sample_id'), table_name='rnaseqdataset_referencegenome')
    op.drop_index(op.f('ix_rnaseqdataset_referencegenome_reference_genome_id'), table_name='rnaseqdataset_referencegenome')
    op.drop_table('rnaseqdataset_referencegenome')
    op.drop_table('reference_genome')
    op.drop_table('experiment')
    op.drop_index(op.f('ix__experimentmetadata_taxon_taxon_id'), table_name='_experimentmetadata_taxon')
    op.drop_index(op.f('ix__experimentmetadata_taxon__experimentmetadata_id'), table_name='_experimentmetadata_taxon')
    op.drop_table('_experimentmetadata_taxon')
    op.drop_index(op.f('ix__experimentmetadata_resource_resource_id'), table_name='_experimentmetadata_resource')
    op.drop_index(op.f('ix__experimentmetadata_resource__experimentmetadata_id'), table_name='_experimentmetadata_resource')
    op.drop_table('_experimentmetadata_resource')
    op.drop_index(op.f('ix__experimentmetadata_method_method_id'), table_name='_experimentmetadata_method')
    op.drop_index(op.f('ix__experimentmetadata_method__experimentmetadata_id'), table_name='_experimentmetadata_method')
    op.drop_table('_experimentmetadata_method')
    op.drop_index(op.f('ix__experimentmetadata_experimenttype_experiment_type_id'), table_name='_experimentmetadata_experimenttype')
    op.drop_index(op.f('ix__experimentmetadata_experimenttype__experimentmetadata_id'), table_name='_experimentmetadata_experimenttype')
    op.drop_table('_experimentmetadata_experimenttype')
    op.drop_index(op.f('ix__experimentmetadata_experimentdesign_experiment_design_id'), table_name='_experimentmetadata_experimentdesign')
    op.drop_index(op.f('ix__experimentmetadata_experimentdesign__experimentmetadata_id'), table_name='_experimentmetadata_experimentdesign')
    op.drop_table('_experimentmetadata_experimentdesign')
    op.drop_table('experiment_type')
    op.drop_table('experiment_design')
    op.drop_table('data_format')
    op.drop_table('_experimentmetadata')
    # ### end Alembic commands ###
